name: az_live
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.6
  chewie: ^1.8.1
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9
  camera: ^0.10.5+9
  flutter_webrtc: ^0.10.6
  agora_rtc_engine: ^6.3.0
  record: ^5.2.1
  audioplayers: ^6.0.0
  web_socket_channel: ^3.0.0
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  record_linux: 1.1.1
  
